//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetStore.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeneralResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PetStore.Resources.GeneralResources", typeof(GeneralResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while adding the object \&quot;{0}\&quot; to the repository..
        /// </summary>
        public static string AddPersistenceExceptionCustomMessage {
            get {
                return ResourceManager.GetString("AddPersistenceExceptionCustomMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while adding the object to the repository..
        /// </summary>
        public static string AddPersistenceExceptionDefaultMessage {
            get {
                return ResourceManager.GetString("AddPersistenceExceptionDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain error..
        /// </summary>
        public static string DomainExceptionDefaultMessage {
            get {
                return ResourceManager.GetString("DomainExceptionDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error ocurred while retrieving the object of id \&quot;{0}\&quot; and type \&quot;{1}\&quot; from the repository..
        /// </summary>
        public static string FindPersistenceExceptionCustomMessage {
            get {
                return ResourceManager.GetString("FindPersistenceExceptionCustomMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while retrieving the object from the repository..
        /// </summary>
        public static string FindPersistenceExceptionDefaultMessage {
            get {
                return ResourceManager.GetString("FindPersistenceExceptionDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while persisting the object..
        /// </summary>
        public static string PersistenceExceptionDefaultMessage {
            get {
                return ResourceManager.GetString("PersistenceExceptionDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while removing the object \&quot;{0}\&quot; from the repository..
        /// </summary>
        public static string RemovePersistenceExceptionCustomMessage {
            get {
                return ResourceManager.GetString("RemovePersistenceExceptionCustomMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while removing the object from the repository..
        /// </summary>
        public static string RemovePersistenceExceptionDefaultMessage {
            get {
                return ResourceManager.GetString("RemovePersistenceExceptionDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation error..
        /// </summary>
        public static string ValidationExceptionDefaultMessage {
            get {
                return ResourceManager.GetString("ValidationExceptionDefaultMessage", resourceCulture);
            }
        }
    }
}
